"""Add chat tables

Revision ID: b78625017de4
Revises:
Create Date: 2025-11-15 17:15:25.400298

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b78625017de4"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("timezone", sa.String(length=50), nullable=True),
        sa.Column("location_city", sa.String(length=100), nullable=True),
        sa.Column("location_country", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_is_active"), "users", ["is_active"], unique=False)
    op.create_table(
        "agent_run_logs",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("agent_name", sa.String(length=100), nullable=False),
        sa.Column("context", sa.String(length=100), nullable=False),
        sa.Column("input_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("output_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agent_run_logs_status"), "agent_run_logs", ["status"], unique=False)
    op.create_index(op.f("ix_agent_run_logs_user_id"), "agent_run_logs", ["user_id"], unique=False)
    op.create_table(
        "chat_sessions",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_sessions_user_id"), "chat_sessions", ["user_id"], unique=False)
    op.create_table(
        "connected_accounts",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("provider_account_id", sa.String(length=255), nullable=True),
        sa.Column("provider_email", sa.String(length=255), nullable=True),
        sa.Column("access_token", sa.Text(), nullable=False),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.Column("token_expires_at", sa.DateTime(), nullable=True),
        sa.Column("scopes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("last_sync_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_connected_accounts_status"), "connected_accounts", ["status"], unique=False)
    op.create_index(
        op.f("ix_connected_accounts_token_expires_at"), "connected_accounts", ["token_expires_at"], unique=False
    )
    op.create_index(op.f("ix_connected_accounts_user_id"), "connected_accounts", ["user_id"], unique=False)
    op.create_table(
        "user_preferences",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("quiet_hours_start", sa.String(length=5), nullable=True),
        sa.Column("quiet_hours_end", sa.String(length=5), nullable=True),
        sa.Column("preferred_work_blocks", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("email_tone", sa.String(length=50), nullable=True),
        sa.Column("meeting_preferences", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("auto_reject_high_risk", sa.Boolean(), nullable=True),
        sa.Column("enable_safety_agent", sa.Boolean(), nullable=True),
        sa.Column("enable_preference_learning", sa.Boolean(), nullable=True),
        sa.Column("notification_settings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "chat_messages",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("sender", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["chat_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_messages_session_id"), "chat_messages", ["session_id"], unique=False)
    op.create_table(
        "items",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("source_provider", sa.String(length=50), nullable=False),
        sa.Column("source_account_id", sa.UUID(), nullable=True),
        sa.Column("source_id", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("body_preview", sa.Text(), nullable=True),
        sa.Column("body_full", sa.Text(), nullable=True),
        sa.Column("sender", sa.String(length=255), nullable=True),
        sa.Column("recipients", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("start_datetime", sa.DateTime(), nullable=True),
        sa.Column("end_datetime", sa.DateTime(), nullable=True),
        sa.Column("received_datetime", sa.DateTime(), nullable=True),
        sa.Column("raw_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["source_account_id"], ["connected_accounts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_items_is_archived"), "items", ["is_archived"], unique=False)
    op.create_index(op.f("ix_items_received_datetime"), "items", ["received_datetime"], unique=False)
    op.create_index(op.f("ix_items_start_datetime"), "items", ["start_datetime"], unique=False)
    op.create_index(op.f("ix_items_user_id"), "items", ["user_id"], unique=False)
    op.create_table(
        "action_proposals",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("related_item_id", sa.UUID(), nullable=True),
        sa.Column("agent_name", sa.String(length=100), nullable=False),
        sa.Column("action_type", sa.String(length=100), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("risk_level", sa.String(length=50), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("warning_text", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column("executed_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["related_item_id"], ["items.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_action_proposals_expires_at"), "action_proposals", ["expires_at"], unique=False)
    op.create_index(op.f("ix_action_proposals_status"), "action_proposals", ["status"], unique=False)
    op.create_index(op.f("ix_action_proposals_user_id"), "action_proposals", ["user_id"], unique=False)
    op.create_table(
        "item_agent_metadata",
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("importance", sa.String(length=50), nullable=True),
        sa.Column("action_type", sa.String(length=50), nullable=True),
        sa.Column("due_datetime", sa.DateTime(), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("labels", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_scam", sa.Boolean(), nullable=True),
        sa.Column("is_noise", sa.Boolean(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("item_id"),
    )
    op.create_index(op.f("ix_item_agent_metadata_category"), "item_agent_metadata", ["category"], unique=False)
    op.create_index(op.f("ix_item_agent_metadata_due_datetime"), "item_agent_metadata", ["due_datetime"], unique=False)
    op.create_index(op.f("ix_item_agent_metadata_importance"), "item_agent_metadata", ["importance"], unique=False)
    op.create_index(op.f("ix_item_agent_metadata_is_scam"), "item_agent_metadata", ["is_scam"], unique=False)
    op.create_table(
        "execution_logs",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("action_proposal_id", sa.UUID(), nullable=False),
        sa.Column("executor_status", sa.String(length=50), nullable=False),
        sa.Column("executor_error", sa.Text(), nullable=True),
        sa.Column("external_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("request_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("response_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("execution_duration_ms", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["action_proposal_id"], ["action_proposals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_execution_logs_action_proposal_id"), "execution_logs", ["action_proposal_id"], unique=False
    )
    op.create_index(op.f("ix_execution_logs_executor_status"), "execution_logs", ["executor_status"], unique=False)
    op.create_index(op.f("ix_execution_logs_user_id"), "execution_logs", ["user_id"], unique=False)
    op.create_table(
        "preference_signals",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=True),
        sa.Column("action_proposal_id", sa.UUID(), nullable=True),
        sa.Column("signal_type", sa.String(length=50), nullable=False),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["action_proposal_id"], ["action_proposals.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_preference_signals_action_proposal_id"), "preference_signals", ["action_proposal_id"], unique=False
    )
    op.create_index(op.f("ix_preference_signals_signal_type"), "preference_signals", ["signal_type"], unique=False)
    op.create_index(op.f("ix_preference_signals_user_id"), "preference_signals", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_preference_signals_user_id"), table_name="preference_signals")
    op.drop_index(op.f("ix_preference_signals_signal_type"), table_name="preference_signals")
    op.drop_index(op.f("ix_preference_signals_action_proposal_id"), table_name="preference_signals")
    op.drop_table("preference_signals")
    op.drop_index(op.f("ix_execution_logs_user_id"), table_name="execution_logs")
    op.drop_index(op.f("ix_execution_logs_executor_status"), table_name="execution_logs")
    op.drop_index(op.f("ix_execution_logs_action_proposal_id"), table_name="execution_logs")
    op.drop_table("execution_logs")
    op.drop_index(op.f("ix_item_agent_metadata_is_scam"), table_name="item_agent_metadata")
    op.drop_index(op.f("ix_item_agent_metadata_importance"), table_name="item_agent_metadata")
    op.drop_index(op.f("ix_item_agent_metadata_due_datetime"), table_name="item_agent_metadata")
    op.drop_index(op.f("ix_item_agent_metadata_category"), table_name="item_agent_metadata")
    op.drop_table("item_agent_metadata")
    op.drop_index(op.f("ix_action_proposals_user_id"), table_name="action_proposals")
    op.drop_index(op.f("ix_action_proposals_status"), table_name="action_proposals")
    op.drop_index(op.f("ix_action_proposals_expires_at"), table_name="action_proposals")
    op.drop_table("action_proposals")
    op.drop_index(op.f("ix_items_user_id"), table_name="items")
    op.drop_index(op.f("ix_items_start_datetime"), table_name="items")
    op.drop_index(op.f("ix_items_received_datetime"), table_name="items")
    op.drop_index(op.f("ix_items_is_archived"), table_name="items")
    op.drop_table("items")
    op.drop_index(op.f("ix_chat_messages_session_id"), table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_table("user_preferences")
    op.drop_index(op.f("ix_connected_accounts_user_id"), table_name="connected_accounts")
    op.drop_index(op.f("ix_connected_accounts_token_expires_at"), table_name="connected_accounts")
    op.drop_index(op.f("ix_connected_accounts_status"), table_name="connected_accounts")
    op.drop_table("connected_accounts")
    op.drop_index(op.f("ix_chat_sessions_user_id"), table_name="chat_sessions")
    op.drop_table("chat_sessions")
    op.drop_index(op.f("ix_agent_run_logs_user_id"), table_name="agent_run_logs")
    op.drop_index(op.f("ix_agent_run_logs_status"), table_name="agent_run_logs")
    op.drop_table("agent_run_logs")
    op.drop_index(op.f("ix_users_is_active"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
